name = "portfolio"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-10-06"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

[vars]
PUBLIC_SANITY_PROJECT_ID = "7blsog1k"
PUBLIC_SANITY_DATASET = "production"
PUBLIC_SANITY_STUDIO_URL = "/studio"
